### PR TITLE
Updated ImGui to 1.60

### PR DESCRIPTION
**Pull request by jreach-dev**
Both examples now work with ImGui 1.60

### CODE REVIEW

**Comment by JoshuaBrookover** [comment]
Thanks!

**Comment by jreach-dev** [comment]
@JoshuaBrookover  No problem. I also updated bgfx but havn't pushed yet because it depends on your bgfx.cmake. Will fork that and do pull request as well.

Any idea on how to make texturev work or is it supposed to fail?

**Comment by JoshuaBrookover** [comment]
It works for me on Mac if I update to the latest bgfx.cmake. I start getting errors in bigg_imgui.hpp, but they are easily fixed. bx::fmin and bx::fmax were removed, so if I change to just fmin and fmax, I'm back up and running.

I see you've made the same fixes in #4

**Comment by jreach-dev** [comment]
Great. It appears updating fixed the texturev issue as well which is currently your only open issue 😃

**Comment by JoshuaBrookover** [comment]
Yes. Thank you for that!

**Comment by jreach-dev** [comment]
Thank you for taking the time to decouple all the components in bigg so cleanly. Makes it very easy to maintain.

**Pull request merged**
